### ISSUE TITLE
[META] demos: come up with javascript for ____ users

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide-examples#1]
@hamilton commented on [Thu Dec 07 2017](https://github.com/iodide-project/iodide/issues/195)

We need to have demo notebooks that mirror some of the rosetta stone type docs out there for other languages:

- [ ] javascript for R users
- [ ] javascript for NumPy users
- [ ] javascript for Matlab users
- [ ] javascript for Julia users
