### ISSUE TITLE
[meta] we should aim for "cheat sheets" like these https://www.rstudio.com/resources/cheatsheets/

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide-examples#7]
these cheat sheets are a great idea
https://www.rstudio.com/resources/cheatsheets/

would be great to have information-dense, runnable overviews if we can think of a way to do it.

for things built into Iodide:
- [ ] how to load data
-

for key libraries:
- [ ] how to plot easily and quickly
    - [ ] with plotly
    - [ ] with metrics graphics
    - [ ] ???? need to find leading libraries!!!
- [ ] how to manipulate data
    - [ ] ???? need to find leading libraries!!!

**Comment by pradeepgangwar** [comment]
@bcolloran I am working on having a plotly notebook demonstrating how to use plotly in effective ways.

**Comment by bcolloran** [comment]
That's perfect! Looking forward to seeing @pradeepgangwar!
